### ISSUE TITLE
extendDeep

### ISSUE THREAD

**Issue by dvv** [akidee/extensions.js#1]
Hi! Discovered a subtle issue: deeply extending {} with an object with an array property results in array being transformed to object: `['a', 'b'] --> {'0': 'a', '1': 'b'}`. It prevents from schema validation using `enum` which must be essentially an array.

--dvv

**Comment by akidee** [comment]
Commit: http://github.com/akidee/extensions.js/commit/af0744bfe45e64e1a786647fdc92b138b1c0e1da
Tell me if it works

**Comment by dvv** [comment]
Works. Thanks!

**Comment by akidee** [comment]
Closed.
